export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'
export const FETCH_CATEGORY_POSTS = 'FETCH_CATEGORY_POSTS'

export const FETCH_POSTS = 'FETCH_POSTS'
export const POST_WAS_CREATED = 'POST_WAS_CREATED'
export const POST_SORT_ORDER = 'POST_SORT_ORDER'
export const POST_WAS_DELETED = 'POST_WAS_DELETED'
